version: "3.8"
services:
  db:
    image: postgres:11-alpine
    container_name: workout-db
    environment:
      POSTGRES_PASSWORD: workout
      POSTGRES_USER: workout
      POSTGRES_DB: workout
    ports:
      - "5432:5432"
    volumes:
      - workout-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  workout-data: