"""create initial tables

Revision ID: b6b0d8ed5d5e
Revises: f46a90eb26d6
Create Date: 2025-08-13 19:59:08.702024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6b0d8ed5d5e'
down_revision: Union[str, Sequence[str], None] = 'f46a90eb26d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('centros_treinamento',
    sa.Column('pk_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('pk_id')
    )
    op.drop_table('centro_treinamento')
    op.add_column('atletas', sa.Column('altura', sa.Float(), nullable=False))
    op.drop_constraint(op.f('atletas_centro_treinamento_id_fkey'), 'atletas', type_='foreignkey')
    op.create_foreign_key(None, 'atletas', 'centros_treinamento', ['centro_treinamento_id'], ['pk_id'])
    op.drop_constraint(op.f('categorias_nome_key'), 'categorias', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('categorias_nome_key'), 'categorias', ['nome'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'atletas', type_='foreignkey')
    op.create_foreign_key(op.f('atletas_centro_treinamento_id_fkey'), 'atletas', 'centro_treinamento', ['centro_treinamento_id'], ['pk_id'])
    op.drop_column('atletas', 'altura')
    op.create_table('centro_treinamento',
    sa.Column('pk_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('endereco', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('proprietario', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('pk_id', name=op.f('centro_treinamento_pkey')),
    sa.UniqueConstraint('nome', name=op.f('centro_treinamento_nome_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('centros_treinamento')
    # ### end Alembic commands ###
